modLoader="javafml"
loaderVersion="${fml_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/DashieDev/WolfDogUtilities/issues"
displayURL="https://minecraft.curseforge.com/projects/wolf-dog-utilities"
logoFile="wolfdog_icon.png"


[[mods]] #mandatory
    modId="wolfdogutilities"
    version="${file.jarVersion}"
    updateJSONURL="https://github.com/DashieDev/WolfDogUtilities/blob/1.19.x-master/check_for_updates/update.json"
    displayName="Wolf & Dog Utilities"
    credits="dashiedev"
    authors="dashiedev"
    description="Providing the game with certain utilities for wolves, giving more control of the user for them."
    displayTest="NONE"
[[dependencies.wolfdogutilities]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.wolfdogutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.wolfdogutilities]]
    modId="doggytalents"
    mandatory=false
    versionRange="[1.4.1,)"
    ordering="NONE"
    side="SERVER"
